name: rag-chatbot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - langchain==0.1.20
      - langchain-community==0.0.38
      - faiss-cpu==1.8.0
      - sentence-transformers==2.7.0
      - unstructured==0.13.7
      - pypdf==4.2.0
      - ollama==0.2.1
      - streamlit==1.35.0
      - fpdf2==2.7.9          # only needed for generate_data.py
      - ipykernel